profile: light
ceip_policy_disclosed: true # Installation fails if this is set to 'false'


# https://docs.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-tanzu-build-service-install-tbs.html#install-tanzu-build-service-by-using-the-tanzu-cli-1
buildservice:
  kp_default_repository: dev.local:5000/build-service
  kp_default_repository_username: user
  kp_default_repository_password: password
  tanzunet_username: USERTANZU
  tanzunet_password: PASSTANZU
  enable_automatic_dependency_updates: true

supply_chain: basic

cnrs:
  domain_name: "apps.example.com"
  
ootb_supply_chain_basic:
  registry:
    server: dev.local:5000
    repository: supply-chain
  gitops:
    ssh_secret: ""

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "example.com"
  app_config:
    app:
      baseUrl: http://tap-gui.example.com
    catalog:
      locations:
        - type: url
          target: https://github.com/benwilcock/tap-gui-blank-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.example.com
      cors:
        origin: http://tap-gui.example.com

metadata_store:
  app_service_type: LoadBalancer 

contour:
  envoy:
    service:
      type: LoadBalancer


